version: "3.9"
services:
  # mendeklarasikan list of services yang ingin kita launch
  pgsql:
    # kita akan menggunakan docker image yang kita milii
    image: postgres:15.4-alpine3.18
    environment:
      # kita bisa mengcopy dari github ci workflow
      - POSTGRES_USER=tech_school
      - POSTGRES_PASSWORD=21204444  
      - POSTGRES_DB=simple_bank



  api:
    build:
      # . = current root folfer
      context: . 
      # memberitahukan docker untuk mencari docker file untuk membuat image
      dockerfile: Dockerfile
    
    # mempublish port 8080 to the host machine so that we can call bank-mandiri api from the outside of the container
    ports:
      - "8080:8080"
    
    # tell api service how to connect to pq service
    environment:
      # ini akan meng override env di app.env
      # dan karna berjalan di network yang sama mereka dapat berkomunikasi via nama service
      - DB_SOURCE=postgresql://tech_school:21204444@pgsql:5432/simple_bank?sslmode=disable

    # command: ["/app/main"]
    # ./wait-for host:port|url [-t timeout] [-- command args]
    # ./wait-for pgsql:5432 -- /app/main
    entrypoint: ["/app/wait-for.sh","pgsql:5432", "--", "/app/main"]
    # entrypoint mengoverride CMD pada dockerfile yang dijalankan oleh docker-compose. sehingga kita harus secara explisit menulis lagi CMD command pada dockerfile
